version: "3"
services:
  app:
    build: .
    depends_on:
      - db
    links:
      - db
    ports:
      - "80:80"

  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE_USER=root
      - MYSQL_DATABASE_PASSWORD=root
      - MYQL_DATABASE_DB=squadmakers
      - MYSQL_DATABASE_HOST=localhost
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./db/schemas:/docker-entrypoint-initdb.d/:ro