version: "3"
services:
  app:
    build: .
    links:
      - db
    ports:
      - "80:80"

  db:
    image: mysql:latest
    ports:
      - "30000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db/schemas:/docker-entrypoint-initdb.d/:ro